### ISSUE TITLE
Upgrade to React 18

### ISSUE THREAD

**Issue by ruudhaya** [zykarsolutions/React-Material-UI-Admin#2]

**Comment by mosesmwila** [comment]
HI, @ruudhaya thanks for getting in touch . The temeplate is actually using React 18.2.0. I forgot to uodate the Read Me file. I will do that.
Thank you once more.

**Comment by ruudhaya** [comment]
Thanks for confirming, Feel free to add the pending features in the issue list. It will help people contribute back :)
Thanks again for sharing this as open source
